# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20170712_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
